package com.thrane.simon.passthebomb.Models;

/**
 * Created by Søren on 26-11-2017.
 */

public enum Category {
    GENERAL_KNOWLEDGE, BOOKS, FILM, MUSIC, MUSICALS_AND_THEATRES, TELEVISION, VIDEO_GAMES, BOARD_GAMES, SCIENCE_AND_NATURE, COMPUTERS, MATHEMATICS, MYTHOLOGY, SPORTS, GEOGRAPHY, HISTORY, POLITICS, ART, CELEBRITIES, ANIMALS, VEHICLES, COMICS, GADGETS, ANIME_AND_MANGA, CARTOON_AND_ANIMATIONS
}
